Repository baokuro04122000/backend-dog-recue-center, pull requests merged in 2023-02, with the labels that each got.

#5 DRCP-25_Design-Docker-file
  .dockerignore
  Dockerfile
  package-lock.json
  package.json
  rest-http/auth.http
  src/server.ts
  src/v1/controllers/auth.controller.ts
  src/v1/services/auth.service.ts
Labels: feat

#6 Drcp 25 design docker compose
  .dockerignore
  Dockerfile
  docker-compose.yml
  package.json
Labels: deploy

#7 fix<DRCP-25>: fix some bugs to deploy
  .env
  .gitignore
  Dockerfile
  docker-compose.yml
  nginx.conf
  package-lock.json
  package.json
  src/index.ts
  src/server.ts
  src/v1/controllers/auth.controller.ts
  src/v1/models/token.mysql.model.ts
  src/v1/services/auth.service.ts
  src/v1/types/user.type.ts
Labels: deploy

#8 feat<DRCP-28>: API forgot password
  .env.example
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
  rest-http/auth.http
  src/index.ts
  src/v1/controllers/auth.controller.ts
  src/v1/lang/en.lang.ts
  src/v1/models/token.mysql.model.ts
  src/v1/routers/auth.router.ts
  src/v1/services/auth.service.ts
  src/v1/types/user.type.ts
  src/v1/validations/auth.validation.ts
Labels: feat

#10 Drcp 30 ci cd codebuild
  buildspec.yml
Labels: bug

#11 Drcp 30 ci cd codebuild
  Dockerfile
Labels: bug

#12 Drcp 30 ci cd codebuild
  Dockerfile
  buildspec.yml
Labels: bug

#14 test<DRCP-23>: unit test
  rest-http/auth.http
  src/v1/controllers/auth.controller.ts
  src/v1/lang/en.lang.ts
  src/v1/validations/auth.validation.ts
  test-report.html
  tests/activeAccount.test.ts
  tests/apiAuth.test.ts
  tests/forgotPassword.test.ts
  tests/signIn.test.ts
  tests/signUp.test.ts
Labels: test

#15 DRCP-31-API-Dogs-get-add-edit-list-pagination-search
  .env
  .env.example
  .sequelizerc
  Dockerfile
  buildspec.yml
  docker-compose.yml
  package-lock.json
  package.json
  rest-http/auth.http
  rest-http/dog.http
  src/migrations/add-column-user.js
  src/server.ts
  src/types/express/index.d.ts
  src/v1/config/database.js
  src/v1/controllers/auth.controller.ts
  src/v1/controllers/dogs.controller.ts
  src/v1/databases/init.mongo.ts
  src/v1/lang/en.lang.ts
  src/v1/middlewares/token.middleware.ts
  src/v1/models/dogs.mysql.model.ts
  src/v1/models/token.mysql.model.ts
  src/v1/models/users.mysql.model.ts
  src/v1/routers/dogs.router.ts
  src/v1/services/auth.service.ts
  src/v1/services/dogs.service.ts
  src/v1/types/dogs.type.ts
  src/v1/types/generic.type.ts
  src/v1/types/user.type.ts
  src/v1/utils/apiFeatures.util.ts
  src/v1/validations/dogs.validation.ts
  test.js
  tsconfig.json
Labels: feat
